### ISSUE TITLE
Issue installing with poetry

### ISSUE THREAD

**Issue by AdrienDart** [azmyrajab/polars_ols#1] opened 2024-04-03 09:55 UTC
Hi,

Thank you very much for your work, much appreciated!

I seem to have an issue with the installation.

"ChefBuildError

Backend 'maturin' is not available.
...
ModuleNotFoundError: No module named 'tomllib'

During the handling of the above exception, another exception occurred:

...
...\sites-packages\maturin\__init__.py
import tomli as tomllib # type: ignore
ModukeNotFoundError: No module named 'tomli'
...

Note: this error originates from the build backend, and is likely not a problem with poetry but with polars-ols (0.1.1) not supporting PEP 517 builds. You can verify this by running 'pio wheel --no-cache-dir --use-pep517 "polars-ols (==0.1.1)" '
"

I have tomli installed in my poetry project.

I believe polars_ds is using a similar project architecture and I experienced no issue like that with that package.

Any help would be appreciated!

Thanks again !

**Comment by azmyrajab** [comment] 2024-04-03 10:46
Hi Adrien, thank you for raising the issue - and glad you think this package may be useful 

Happy to look into this for you - mind if I start by asking you what platform / architecture / OS you are on?

Github CI tests cover most (but not all) Linux and macOS systems but not windows yet. I can then hopefully reproduce your issue on the server and try to get it fixed

**Comment by azmyrajab** [comment] 2024-04-03 10:49
Also if you could share your python version that would be helpful too!

**Comment by AdrienDart** [comment] 2024-04-03 12:09
Hi, thank you for your reply! I am using Python 3.9.0 from a poetry environment on a Windows machine.

**Comment by azmyrajab** [comment] 2024-04-03 20:30
Hi @AdrienDart  

windows support should be ready which should resolve the issue (see https://github.com/azmyrajab/polars_ols/commit/6a30e8c02014cf25076cde28c29e800d4fe39b41, and latest CI tests just passed)

So I'll let you know once the new pypy tag is released and you could try it out again? Will bundle in another improvement to how coefficients are outputted.

**Comment by AdrienDart** [comment] 2024-04-03 21:20
Amazing! Take your time and again, thank you for your work!

**Comment by azmyrajab** [comment] 2024-04-04 14:17
Hi @AdrienDart  can you try installing again, just released v0.2.0 which should support windows OS

Could you please let me know if this resolves your issue?

**Comment by AdrienDart** [comment] 2024-04-04 14:41
Hi, I just tried and I unfortunately got the same error message (with version 0.2.0 obviously). I'll migrate towards python 3.9.5 in a few days, maybe that will change something. Not sure what is causing this issue.

**Comment by azmyrajab** [comment] 2024-04-04 15:58
Feel free to try again whenever you can and let me know if it works for you now. Tests here indicate py38 windows succeeds
If forever reason it doesn't, let's wait until you upgrade to 3.9 and see if that resolves it

**Comment by AdrienDart** [comment] 2024-04-05 06:56
Hi, unfortunately, I get the same error with version 0.2.3.

**Comment by azmyrajab** [comment] 2024-04-05 07:47
Strange. Unfortunately, I can’t reproduce on the windows test I am able to run on my side. 

Whenever you could, can you please try installing manually with pip install in a new venv. And if errors copy the stack trace here. It will help us understand if this is specific to a poetry install or the specifics of your system so I can hopefully reproduce. 

Sorry about this!

**Comment by AdrienDart** [comment] 2024-04-05 08:15
No worries. I tried on a new venv running python 3.9.5. I manage to install polars and polars-ds on it with pip (24.0). When trying to do polars-ols, I got the following error:

"
(...)
Preparing metadata (pyproject.toml) ... error 

x Preparing metadata (pyproject.toml) did not run successfully 
exit code: 1
Cargo, the Rust package manager, is not installed or not on PATH. This package requires Rust and Cargo to compile extensions. Install it though the system's package manager ot via https://rustup.rs/
Checking for Rust toolchain...

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

x Encountered error while generating package metadata.

(...)
"

**Comment by azmyrajab** [comment] 2024-04-05 21:50
Hi @AdrienDart 

I managed to finally reproduce your issue (..on an Azure windows VM) - and specifically on py39 but on no later versions (e.g. py312). 
So after some digging - I found the culprit to be this pyo3: [feature flag](https://github.com/azmyrajab/polars_ols/commit/7230d0ae795cf0a910d1a094650c842666d065d1#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) in cargo.toml 

Changing it to py38 from py310 means pyo3 (which is responsible for the rust bindings in python) must ensure wheels produced are compatible since py38+. Given my code is already backwards compatible, it made sense to change it
`pyo3 = { version = "*", features = ["extension-module", "abi3-py38"] }  # set > py38 supported version`

After releasing to PyPI the latest version (0.2.4):
<img width="615" alt="image" src="https://github.com/azmyrajab/polars_ols/assets/9899436/a5b6b9eb-e47b-4e8f-9df0-d4ff51c36c87">

Closing as this should now resolve your issue, whenever you can upgrade - but please do confirm that all is smooth when you have a chance!

**Closed by azmyrajab** 2024-04-05 21:50 UTC

**Comment by AdrienDart** [comment] 2024-04-08 06:54
I can confirm that installation now works! Thank you for the package and for looking into this!
